### ISSUE TITLE
Should ValueSuggest force selection of a value?

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/ValueSuggest#14]
With a resource template with a property set to use something from value suggest, I can still enter plain text values.

To reproduce:

* Create a resource template with a property using a data type from Value Suggest
* Edit/add an Item with that template and property
* Type something in to the input field to bring up the dropdown
* _Without_ selecting anything from the dropdown, save the new item

Looks like the text input string is what gets saved

**Comment by jimsafley** [comment]
ValueSuggest was conceived to _suggest_ values, not require ones from a list. Even so, I'm not in favor of such a feature because the autosuggest services, while helpful in many cases, often don't return an exact match. Restricting values to suggestions is not within the spirit of the module. Use CustomVocab for the something-from-the-list-or-nothing approach.

**Comment by patrickmj** [comment]
Ok. That distinction should be noted in the documentation from @mebrett and team.
