### ISSUE TITLE
add support for wikidata

### ISSUE THREAD

**Issue by tdombos** [omeka-s-modules/ValueSuggest#21]
It would be great to be able to use https://www.wikidata.org as a source for terms.

**Comment by jimsafley** [comment]
Since Wikidata is clearinghouse of linked data from many domains, a Wikidata suggester would need its own separate UI so users could select specific domains from which to fetch results. Otherwise, the results would be useless in their abundance and disorganization. Perhaps we could make this interface, but not in the foreseeable future.

**Comment by tdombos** [comment]
Having extra UI for selecting a subset of wikidata items would indeed be useful, but I do not agree that  "results would be useless in their abundance and disorganization". I've been using wikidata as a source for tagging in drupal based websites (https://www.drupal.org/project/yild) and it works very well.

**Comment by nishad** [comment]
We created an Omeka-S module based on ValueSuggest for auto-suggest Wikidata URIs and labels. https://github.com/nishad/omeka-s-wikidata. Planning to add some UI for filtering the search scope.

**Comment by jimsafley** [comment]
@nishad Thank you for doing this! Typically, developers submit a pull request to this repository if they want to contribute a suggester that would benefit the community, but I'm sure you have good reason to create a new module. If you don't plan to submit a PR, please consider [registering your module](https://omeka.org/register/) so we can publish it on the Omeka website.

**Comment by nishad** [comment]
@jimsafley, as you mentioned in this thread, Wikidata cannot be treated as normal vocabulary. Instead of making it as a part of valuesuggest, we decided to treat it as a separate module for developing Wikidata specific features such as configurable filters, and options to create advanced filters through SPARQL etc. We are also working on moving some API queries to client-side for performance and saving resources. One of our use-cases is to pre-populate a custom list of Wikidata URIs.
