### ISSUE TITLE
Adding support for Tematres instances

### ISSUE THREAD

**Issue by tematres** [omeka-s-modules/ValueSuggest#47]
Hi, we want to add Tematres (open source controlled vocabulary server) capabilities to serve terminological suggestions to the ValueSuggest plug-in. In the past, we achieved add to Omeka Classic Plug-in the Tematres terms suggestion services (in this case usign standard way provided by Tematres). Here the forked plug-in: https://github.com/tematres/plugin-LcSuggest

In the case of TermSuggested for Omeka-S, we explore different ways to try to add the tematres services to the plug-in.
We do not have experience about Omeka framework :/

We try (and failed) to add tematres to the plug-in following these 4 ways:

We create a proxy who follow the documentation: 
  /**
     * Get an array of suggestions given a query.
     *
     * Implementations should return an array in the following format:
     *
     * [
     *   [
     *     'value' => <value>,
     *     'data' => [
     *       'uri' => <uri>,
     *       'info' => <info>,
     *     ],
     *   ],
     *   <...>
     * ]
     *
     * <value>: (required) the suggestion text, preferably in the passed language
     * <uri>: (optional) the suggestion's canonical URI
     * <info>: (optional) any disambiguating text, preferably in the passed language
     
You can test here: https://vocabularyserver.com/lab/suggester/?query=fest

and here with JSONP: https://vocabularyserver.com/lab/suggester/?callback=jQuery21004099131743997906_1573499562767&query=fiest

We have a specific command provided in the Tematres web services interface:

Here example to UNBIS thesaurs (https://www.vocabularyserver.com/unbis/en/api/)

In XML: https://www.vocabularyserver.com/unbis/en/api/suggest/languag

In JSON: https://www.vocabularyserver.com/unbis/en/api/suggest/languag/json

We can use dedicated endpoint provided by tematres to segguest terms:

Here example:
https://www.vocabularyserver.com/unbis/en/suggest.php?query=languag

In addition, we can use the SPARQL endpoint provider by tematres (we use ARC2). In this case, we have enabled the POST method.

Here example: https://r020.com.ar/tematres/demo/sparql.php

Can you help us in any way to adding support for Tematres instances in valueSuggest?

Thank you in advance and sorry about my english.

======= examples =====
here some examples about Tematres web API:
Hi, Tematres is a open source tool to manage formal representations of knolodge (aka: controlled vocabularies). There are more than 500 know cases who use Tematres (https://www.vocabularyserver.com/vocabularies/). Tematres provide a specializated web API. Here some documentation: https://www.vocabularyserver.com/wiki/

There are a familiy of tools who use the Tematres web services, here some of them:

- Portalthes: (include feedback, terminological bulk analysis, and more)
https://www.vocabularyserver.com/portalthes/index.php?v=

- PopTerm: 
https://www.vocabularyserver.com/popterms/

- Examples about use tematres web services:
https://www.vocabularyserver.com/examples/
https://www.vocabularyserver.com/examples/autocompletar.php

**Comment by jimsafley** [comment]
Since TemaTres is a vocabulary server that appears to contain over 600 vocabularies, please consider creating a separate module to add the vocabularies as ValueSuggest data types, e.g. `valuesuggest:tematres:unbis`. You can use existing ValueSuggest data types as examples of how to add vocabularies, but here's a general overview:

- Register your vocab in module.config.php, in `data_types[factories]` - e.g. `valuesuggest:tematres:unbis`
- From the factory, inject whatever services you need in the data type
- Your data type should extend `ValueSuggest\DataType\AbstractDataType`
- Your data type should return the suggester object from `getSuggester()`
- Your suggester should implement `ValueSuggest\Suggester\SuggesterInterface`
- Your suggester should return the suggestions array from `getSuggestions()`

Again, take a look at the many other vocabularies in ValueSuggest to get a more detailed view of how to implement your vocabularies.

**Comment by tematres** [comment]
Hi @jimsafley :) here there are a fork from ValueSuggest to omeka-s who can use tematres sources of data: https://github.com/tounoki/ValueSuggest

In addition, there are a fork from LcSuggest (to omeka classic) who  can use tematres sources of data too.
Sorry about my english :/
