### ISSUE TITLE
Some drop down suggested choices aren't showing and not in the Collecting Form module. 

### ISSUE THREAD

**Issue by GitByrd** [omeka-s-modules/ValueSuggest#52]
Hi, I noticed that some vocabularies provide drop down choices, such as RDA: Material, but others, like LC:MARC:countries, doesn't provide a list of of countries. 

More importantly though, the ones that I know that provide a drop down of choices like RDA: Material, when added as a data type field on the Collecting Form, it doesn't provide the drop down of choices anymore on the live form, as it would when adding an item in the system. 

Is this something that I should also mark as an issue in the Collecting Form module?  

Thanks.

**Comment by jimsafley** [comment]
**RDA: Material** and **LC: MARC Countries** differ in the way they request values from their respective endpoints, which explains the difference of behavior. The former uses the "valuesuggestall" strategy, which assumes the first request contains all possible values, and so it displays all values when the text box is in focus. The latter uses the default "valuesuggest" strategy, which assumes the list of possible values _may be_ large and therefore needs multiple requests, and so it displays relevant values only after the user inputs 3-or-more characters into the text box.

As far as I know, there is no interaction between ValueSuggest and Collecting. ValueSuggest only enables suggestions on values of resources that have a resource template, and Collecting has no such feature.

**Comment by GitByrd** [comment]
Oh thank you, I didn't realize you had to type in three characters...I see that working now! 

As far as the Collecting Module, I just assumed it work work, since you can choose the data type of Value Suggest and the vocabulary when building the form on the right hand side. Otherwise if there's no intentional interaction between ValueSuggest and Collecting, why would it present this as a choice when building the form?  I am able to add the data type of "Custom Vocabulary" and the choices do end up auto populating on the live form with that module.

**Comment by jimsafley** [comment]
I suspect that you're using [Daniel-KM's Collecting module](https://github.com/Daniel-KM/Omeka-S-module-Collecting), not [ours](https://github.com/omeka-s-modules/Collecting). I recommend you open an issue over there.

**Comment by GitByrd** [comment]
Ok, will do, thanks!

**Comment by Daniel-KM** [comment]
Indeed, if you use my fork of the module [Collecting](https://github.com/Daniel-KM/Omeka-S-module-Collecting), you should use the fork of [Value Suggest](https://github.com/Daniel-KM/Omeka-S-module-ValueSuggest) too. 

Anyway, these forks will be deprecated soon: the main issue I have is that it is long for the admin to create forms with Collecting, in particular with multiple translated sites (but this issue was fixed separately in module [Internationalisation](https://github.com/Daniel-KM/Omeka-S-module-Internationalisation)), and they are not in sync with the resource templates. So I created the module [Contribute](https://github.com/Daniel-KM/Omeka-S-module-Contribute) that uses the resources templates as a base for the collecting forms. So it's possible to use any datatype, included Value Suggest or Custom Vocab. Furthermore, this module allows the public to correct and complete records (via the integration of my module Correcting, that will be deprecated soon too). There are still some small issues to fix.
