### ISSUE TITLE
Feature Request: Nomenclature

### ISSUE THREAD

**Issue by morarchives** [omeka-s-modules/ValueSuggest#69]
Many museums use Nomenclature for identifying their objects. It does not have an API yet but could any of the other integration formats they have available be used?

https://www.nomenclature.info/integration.app?lang=en

Thanks

**Comment by jimsafley** [comment]
As you are aware, we designed this module primarily to make requests against an existing, remote endpoint. The module does serve very small datasets, like for Dublin Core, but we hesitate to serve larger datasets because it would require a) building our own endpoint or b) putting the entire dataset in memory for every request.

That said, I notice that Nomenclature has an undocumented API that provides suggestions, like [this query](https://www.nomenclature.info/api/autosuggestion/search-keywords?key=cabin&wp=N&lp=INT&l=en&term=cabin) for "cabin." Problem is, the response does not include URIs, which would be necessary for a complete implementation.

**Comment by morarchives** [comment]
Okay, thanks for looking at it

**Comment by jimsafley** [comment]
Nomenclature published a SPARQL endpoint since this issue was created. Added a suggester in 72fbb386af76c25181e91b2014ace4798fb77c93
